import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignOutButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { MdPerson } from "react-icons/md";

import { ClientDevelopments } from "@/components/client-developments";
import { LoggedOutTop } from "@/components/logged-out-top";
import { ServerDevelopments } from "@/components/server-developments";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedIn>
            <header>
              <nav>
                <SignOutButton />
                <Link
                  href="/mypage"
                  className={cn(
                    buttonVariants({ variant: "outline" }),
                    "border border-slate-400",
                  )}
                >
                  <MdPerson size={24} />
                </Link>
              </nav>
            </header>
            {children}
          </SignedIn>
          <SignedOut>
            <LoggedOutTop />
          </SignedOut>
          <div className="fixed bottom-0 flex flex-col gap-4">
            <ClientDevelopments />
            <ServerDevelopments />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
